apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-manager-access-sa
  namespace: verifications-staging-namespace
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ID}:role/justaname-staging-cluster-eksClusterRole
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: verifications-staging-namespace
  annotations:
    last-modified: "2024-04-04"
spec:
  provider: aws
  secretObjects:
    - secretName: foosecret-verifications
      type: Opaque
      data:
        - objectName: infura_project_id
          key: INFURA_PROJECT_ID
        - objectName: signing_private_key
          key: SIGNING_PRIVATE_KEY
        - objectName: signing_private_key_sepolia_domain
          key: SIGNING_PRIVATE_KEY_SEPOLIA_DOMAIN
        - objectName: environment
          key: ENVIRONMENT
        - objectName: api_domain
          key: API_DOMAIN
        - objectName: github_client_id
          key: GITHUB_CLIENT_ID
        - objectName: github_client_secret
          key: GITHUB_CLIENT_SECRET
        - objectName: twitter_client_id
          key: TWITTER_CLIENT_ID
        - objectName: twitter_client_secret
          key: TWITTER_CLIENT_SECRET
        - objectName: telegram_bot_token
          key: TELEGRAM_BOT_TOKEN
        - objectName: telegram_bot_username
          key: TELEGRAM_BOT_USERNAME
        - objectName: discord_client_id
          key: DISCORD_CLIENT_ID
        - objectName: discord_client_secret
          key: DISCORD_CLIENT_SECRET
        - objectName: ens_domain
          key: ENS_DOMAIN
        - objectName: ens_domain_sepolia
          key: ENS_DOMAIN_SEPOLIA
        - objectName: jwt_secret
          key: JWT_SECRET
        - objectName: encrypt_key
          key: ENCRYPT_KEY
        - objectName: encrypt_salt
          key: ENCRYPT_SALT
        - objectName: justaname_environment
          key: JUSTANAME_ENVIRONMENT
        - objectName: resend_api_key
          key: RESEND_API_KEY
        - objectName: origin
          key: ORIGIN
        - objectName: domain
          key: DOMAIN


  parameters:
    region: eu-central-1
    objects: |
      - objectName: "justaname-staging-verifications-env-var"
        objectType: "secretsmanager"
        jmesPath:
          - path: INFURA_PROJECT_ID
            objectAlias: infura_project_id
          - path: SIGNING_PRIVATE_KEY
            objectAlias: signing_private_key
          - path: SIGNING_PRIVATE_KEY_SEPOLIA_DOMAIN
            objectAlias: signing_private_key_sepolia_domain
          - path: ENVIRONMENT
            objectAlias: environment
          - path: API_DOMAIN
            objectAlias: api_domain
          - path: GITHUB_CLIENT_ID
            objectAlias: github_client_id
          - path: GITHUB_CLIENT_SECRET
            objectAlias: github_client_secret
          - path: TWITTER_CLIENT_ID
            objectAlias: twitter_client_id
          - path: TWITTER_CLIENT_SECRET
            objectAlias: twitter_client_secret
          - path: TELEGRAM_BOT_TOKEN
            objectAlias: telegram_bot_token
          - path: TELEGRAM_BOT_USERNAME
            objectAlias: telegram_bot_username
          - path: DISCORD_CLIENT_ID
            objectAlias: discord_client_id
          - path: DISCORD_CLIENT_SECRET
            objectAlias: discord_client_secret
          - path: ENS_DOMAIN
            objectAlias: ens_domain
          - path: ENS_DOMAIN_SEPOLIA
            objectAlias: ens_domain_sepolia
          - path: JWT_SECRET
            objectAlias: jwt_secret
          - path: ENCRYPT_KEY
            objectAlias: encrypt_key
          - path: ENCRYPT_SALT
            objectAlias: encrypt_salt
          - path: JUSTANAME_ENVIRONMENT
            objectAlias: justaname_environment
          - path: RESEND_API_KEY
            objectAlias: resend_api_key
          - path: ORIGIN
            objectAlias: origin
          - path: DOMAIN
            objectAlias: domain
